### ISSUE TITLE
Variance when centroids and points are the same

### ISSUE THREAD

**Issue by bobhancock** [bobhancock/goxmeans#14]
When the centroids and the points are exactly the same, this makes the denominator R - K = 0, and produces Nan.

Is it valid to to just return 0 as a variance if the two sets of points are the same?

**Comment by afoglia** [comment]
On Sun, Aug 26, 2012 at 12:31 AM, Bob Hancock notifications@github.comwrote:

> When the centroids and the points are exactly the same, this makes the
> denominator R - K = 0, and produces Nan.
> 
> Is it valid to to just return 0 as a variance if the two sets of points
> are the same?
> 
> You mean the clusters and the data points?  I believe so.  I'm not sure how
> to take the limit to verify, but I'd be surprised if it was any different.

Actually, you should check that the two sets are the same, and each data
point is a member of the cluster whose centroid center is located at the
same point.  There's an unlikely chance that the you can create all the
centroids at the same points as the data, but put all the data into
centroids other than the closest.  That shouldn't happen, and I wouldn't
worry about checking it, because the algorithm should never find such a
case, but to mathematically prove it, you'd need to enforce it somehow.

## 

--Anthony

**Comment by bobhancock** [comment]
Added smoothing.
