### ISSUE TITLE
TestRandCentroids fails

### ISSUE THREAD

**Issue by bobhancock** [bobhancock/goxmeans#7]
./km_test.go:85: cannot use DataCentroids literal (type DataCentroids) as type CentroidChooser in array element:
        DataCentroids does not implement CentroidChooser (wrong type for ChooseCentroids method)
                have ChooseCentroids(_matrix.DenseMatrix, int) (_matrix.DenseMatrix, error)
                want ChooseCentroids(*matrix.DenseMatrix, int) *matrix.DenseMatrix

**Comment by danielhfrank** [comment]
I'll see if I can duplicate this on my home machine - in the meantime, could I ask you for the `testSetSmall.txt` file? Or, alternatively, for a script to generate it? I've been unable to run the full test suite without it

**Comment by bobhancock** [comment]
I had these in my ignore file.  I'll add them to the repository this
afternoon.
On Jul 31, 2012 2:20 PM, "Dan Frank" <
reply@reply.github.com>
wrote:

**Comment by bobhancock** [comment]
I fixed this.  Instead of returning an error, which invalidates the interface, if k > row then k = row.

**Comment by danielhfrank** [comment]
Thanks for updating! Sorry I didn't get to it sooner. I'd had trouble
reproducing, for whatever reason

On Aug 28, 2012, at 3:27 PM, Bob Hancock notifications@github.com wrote:

I fixed this. Instead of returning an error, which invalidates the
interface, if k > row then k = row.

—
Reply to this email directly or view it on
GitHubhttps://github.com/bobhancock/goxmeans/issues/7#issuecomment-8103919.
